name: master

on:
  push:
    branches:
      - master

jobs:

  #--------------------------
  # BUILD
  #--------------------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.5.2

      - name: Install dependencies
        run: flutter pub get

      - name: Build
        run: |
          flutter analyze
          flutter test
          flutter build apk --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk
