name: master

on:
  push:
    branches:
      - master

env:
  FLUTTER_VERSION: "2.5.2"
  PROPERTIES_PATH: "./android/key.properties"
  #--------------------------
  # SECRETS
  #--------------------------
  KEY_STORE: "wutsiwutsi"
  KEY_PASSWORD: "wutsiwutsi"
  KEY_ALIAS: "upload"
  KEY_FILE: "../keystore/upload-keystore2.jks"
  KEYSTORE: "MIIKlQIBAzCCCk4GCSqGSIb3DQEHAaCCCj8Eggo7MIIKNzCCBa4GCSqGSIb3DQEHAaCCBZ8EggWbMIIFlzCCBZMGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFMU+bM+eb7UYCrOFSShb1oR+adzLAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQkrRjifoKkddErnrKx2ZdwQSCBNBP0QIk7701Hu0vg/b5Zi5Wn4U9OZhFeC1NIUItJmaCDDOnoua49cnnrjktMjQkoMuSW2TAOdNVX3YsZKMF3PRZRqlSNy3frzoQ9ngxUwrWzh7SQgbBsLhvBx+vqGwj9hJbS1Igb3g2fuS6bnfxglRLPpNByXi5y0WC18EuWQadpBziHC4NMfWYw65eiqOEZ1CUlvepD9CiL8HC0MSiQxBhPSeNTy+d6NXXNmlqmvmvsWFlJ3PXSHc4bA3UHMGEa3ptHj3CvyKMVQfov/D6RCKF7vpT4wKfuCvl15Bo6wSNJDOl6ZsAlbYIPFikd2ZxtqMXPYskf9OPkxopR15YVa+zc+4Ek+i5ygtvB6gjo7KNNpF7ZTtLfVr4atkbwv1fCzRTavYyYQr1Tkod85Nooj0aQRfXuYRrVYZH8LIzv9YKuydGc/M58Z2vhYDnu0kN1blibHbKZiJJSG7uOBRRHaeaSnUCHF6NZ3c78lEGlgDFyS8RTdXqB+MEr3rXPn4hml0+rVHBLILvA7EnBR9C1fX21YQ5CuVQUuTsdyjeEDahIZlKmHDpeqcUS0Msc4E1LGV9LZQNqzjPMPbt4wrsi0BM1y8p0suoRHjG8EQdo5tenMuAl6daAgE1uJMGOiJ1mHAuWHFM9pH2MvQt/ggHTaMnSIHoUtXk4u0q5QrxXg/U7B1RlXUryZIb9zIWKHasFE7kqDhxhoXcbuCxynIa2bt9/p0pHgtiuPaLGv9tp/Y2IktUcV7uc0m7xCHF73mN0gBoqdiSkN62iUtmkFzCxPfoO7WtbWm5phbBU524O67nFVh0SCXYJXFfFlJJROpuVmurCf2ZjjsHcydTNg1stNEQz8evIjExjxUm4p81Lo7JLxfwGV4TmslKrolUBPtTHPJJ773+PE7xPu5VRcFwC11IasxCABT3zhO0dJjsJ9VWw3FahneFBdLSQZUVKi/JjiNt4n8pFi6PHadYkRSmHvfju7sW1k/cWnogYw6VbC6ORD01sbfq03tkO6KBX1Y5d6BZf3CGz+Q2q8EprQiWrd/qajpWsG4q2COBDrI2j2iqUNS97Y3VS+VVCIY9Cm2JWpXDrLMZCE4WI8RhvmgYU8YqsJpbkZaYoKBRh/gZZzVw2t+Oh9fQ6+rdaTbM3i10ifIpVs46WHLCu/v4kznq4i1VgqZm8oiw5cnwJSbLA/Z3eQShYc8nesedqWlyLVn4qwvWok8I3OCVjbf4wIiA7n/aA3Jc7oPjAr2Q1ZYKq2UxLOM20OhMsrXyvPgFKDGX/qX9P4UXqfHnH74WVmk1Ghby/0wffj7FtuaJ5f4osdDwFu8eoz5hmDS531Qho0B40rIosye3CW5bWrqo2DGomFBUj6LuLd8LAg6bm9B3BtKrCanEUC/5AMgKvJ5pyXFJFkIIY/96Ppbk856mflepx5+T4DGlvlNFmqsgNF834ZVAGfrfDKxrB0JzzHXI+B+YdeTyEarHK2RmsuWPlXiBjzWM/MFXjBZRN+S5+P/js/4U8xZaGyGahOyNlAvqVlrfRwVuZHCoU16XnYX7q09i2cdq/cUaxw7dyzzxgxNDRog5kOWBYosGTlDhXxgS9TvQd/tpdHyKq1eN3knAURkbV8l2hiBqZpCRj9xINtileihBxzFAMBsGCSqGSIb3DQEJFDEOHgwAdQBwAGwAbwBhAGQwIQYJKoZIhvcNAQkVMRQEElRpbWUgMTYzOTI1Mjg1ODEzNzCCBIEGCSqGSIb3DQEHBqCCBHIwggRuAgEAMIIEZwYJKoZIhvcNAQcBMGYGCSqGSIb3DQEFDTBZMDgGCSqGSIb3DQEFDDArBBTKs5UqymEF5g7Q5KzJKa0XvttBVwICJxACASAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEN34hXCDzD6/Y34cbR5HWB+AggPwpUUAYpOVGOsNQFQtoi5Ts55y9GCpmgXfDumeq4cv5WyInzrwYPDSgSp78bLFahLgUqWOrs349sThZuhFYlqoirKwdumt//J4u44q5LJ1w+z6/XeS3IUGrSuRhu6ySfY9bq2kEfvRO4mGI/I9vKSLu53vbVTXP1mfzSV/JM1YPrfPqZWoCEsZQOl1gt2oJdNPRcw64QqbkdymVnrDzn45bqUsSRPtWGrAqyiAcnkny0pivfweWSiZ5HFu7Dgyj6TcPMhY//mbVPug+JWsogA7qe6xw+U6NgF42Eknf61mGzZlwy7sQd9MA0qZBAlqMU3KiWH1+f9rV3dkJWcKZXwm4jgX9nWcJaobfzn+DE8Ee31YlObSUpbsE3duM6x0EQuPQXtus6SrktQPDFYtvG7qR1rKLk111874ygoDd9KXM3M4hbAdcVYEqDToRsJUmMAzlvU3Y1rLvAoUVOhQrw5Na9X6YlKzNpwK/515oRUChXBB/O+5kGzxijq5vghvOZKErUApKEN/I55Npos98HdVK6grUYeNC9HeZV2a7xRmDJgaaCoclJzC5YLgPt2zvNT3hhLme8x4cEYsLz/1TKaeUpOECwBJmLKb/IhCRbL/shYIby/ijrJlBreKVOdDvo49e7XuRlPKfx3sj+tvGd22Ke957+mJyDa6D7YAvUNmPbnu6R6ym15mRLK+pTzn/dBAbbODpNnkKgXyrNkFuPsUa0zWfWf/f3JWhWviLOdGVrBLMrpATI5+iT6jH4mIgCMFSjFDLifub9uJLz/hoKMqMbzkVYU8tjrdp0ZUbdCdOWxK4+ILh0JeYSTXXk2ij4wpSdp9Z6A6EdKauUovye3qIxzUr91QLrp3ZbValt1aiUnjyC6ebVIty/7ykvmPTbA+FdGtBnwSc1ZU/gI2Gu5l0hX/D82U4RsLntIbVs3OL4Vw3FNIpaXC7K+UEQUTGdHreJjdwXff3SDmFdIsOrC2II+aJAzdBSAMC4m1g/l6eHv8ymXNjLUbs4phTHVkDLDaUQ9VP9jneZJuwl762c+UempItDSLk8ZqCx02YZx038tP+NHWLoLpKQdoNerszugPouuurjKuH8nb5jdm2sT2rPfx2wwuQ+GeZxzc0DaBOOn9AN47V4hLKqCdIaERBX6ysBd5Kx/KCHyYJ2cFRIcvVW9fkKtIOMUJ0/v9naj6OsR8pTzUSIdcXdLu1uG6XcCbhxeerySPje/ebPXUEVLGMD4qb/YmPeG1ck1obmpPOScIqd/Rum2iJiDYE44uyaphvutAnGz9MMopqUIcqDe1K644SNQqYS3a3iJ5i9W4kkj8Pu6KDpzfPQ9kFJgUJSHdMD4wITAJBgUrDgMCGgUABBQL2HBXavILhKh1ppCJmMUgZFWejwQUOaKPssYlTGgbUHLc3SWqaUuNjmUCAwGGoA=="

  GOOGLE_SERVICE_JSONKEY: "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAicGMtYXBpLTQ4Njc1MjU0NDg0ODMzMzYwOTAtNjYxIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiMjBiYzM2MjQxMzUxODFmMDU3Y2Q4ODE4ZjFhOWMzNmIxZTc1NzcwZSIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZBSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS1l3Z2dTaUFnRUFBb0lCQVFEam1UUWpCNXUvNEl5RVxuRnYwQVZpNEhiNlY5cFpYRXF0enFuTklnclZaYkZFTVBPM2FmYjJ2OEFndEVvV3plOEtzaDBmQ2pXaFBhUVZEbFxuYTZLZXRXTjNHUk5HSTY4ZHhWQ3diUTBnRCtZOTlRMDRsUWs1MFpPM1FhNVJJeEk3ZFpXVkJqTjA4N0hES2FPNFxuOGRXbEdwbUNvT2kxWmIyVHRPUEJ4M2tzVFpyN3c3aS84WHVoejRsaWhLVy9FMjBYNzRVOVl1OGs1U3pTbjVBWFxuRDJlMlNkMFdhVXdtNlJUdHVncGwra09xUi9RUlFlc0ErdDFyN0I3SXR5WjBsMWt4cWVQZkd2ZHlJQWgrbkhiYlxuKytScm5pRy8rOFZOVkV3VlhpQlZENUkxY3FJWHZrbUcxSXZKWTNSeitHK25jRzZvNUx0Y2J1NmR3bmorQUxrNFxuWHNqaXREUi9BZ01CQUFFQ2dnRUFhR0dFZkVaS2czcnY1c3FHT09mTlQyTEFVcm9rMEdBT1Zsa2FzNXJibm9UUlxuNW9QK2VNdUlpampEd3pPSGMwMk1Kc1FhYVVod0QycGlOLzJmeE1ycXRaM2Q3WTZEQ3hQSjJFZ0RPMytmT0M0UlxuWkxCUlhWK0ZNQWdpOHBvemkrcDI4alE0V0R4RmUveTJWaVV2TnZ2V2lJYlVneEVJbTF2Y0VxeXhvWVJyL21kY1xudjFjYWZ2bDUvVlB2WlY0TzRUTjJVTzRkczQ3NGtUTWpoNDYvbXZUYndkSFA4Z3dBdUdINmZZVnJ3dEtqYWIzWlxuQ0FRWTNsZG9wcy9lTzU1Y3V0b1J6a0hvQTY4ci9ZcGtvYysreTZTdExoRlhyclAwZDBuR1dHL2MwK3EyRmFLQlxuZlJ6VkFHaVNIajVXRkxmYXphVUZqMy8xeEo0cHR4MDVwSmRMVkprVHpRS0JnUUQ5b3V1aGs3Y3BUcVlkV3lNZlxuQlh0dm9kd3RZODJ5Q1Uycmgxb1M1RTdTUElyUjdSYXNBVDRYbmVTc2FtR29tSVAwMXNHd20xT1RFNlF2UlRHSFxucVBzTTlJN0l1bjU3SU1wQnZ2YTdxNlYvT1V2dUdLTmdMNXVocXNZaTFCZ2F4ZWo0K050NExnZU9QVno5UXY4L1xuNUk4ZUk0anZ5UXQ1MlVIVnIvMUtBOG91U3dLQmdRRGx1Q3FtOGtZU0pXUFZ3MTNvV3pzV0owNzY4Uy81YTRqRFxuZGlRc2lrdVBEUG42UHdqeG5WQnloemVuUUdQamlDb2xXaFhOd1B4UEQvUVR4UEIwckJ6REtXeTR0OHpCTTIrUlxuTnA2ekVsaXh4QWM1MXdaM3ZKRnM3MFJDTVpSdDI4aG13aFpvdjNqQVdleXZyOFB0a1NzVTBEbVlPZ2hxTlRLRFxuVzJiTVc1VWlIUUtCZ0hjbFMwOHhscjcreFNYUkpDUjBiTkc1MVRZMVJmRTJVWmdjRXdJQTRjMzh4ckZxa0ZYb1xubDRSOGxXa3c2QU5NOGQvWDZsRE9CbXAydFkvSEQwZE01L0hrQ0JiZkZIOCtuZ1JZY29zaVRMSUE5bHc0a3JhaVxuWnBlQkkyWkUvN1hEOW5iT1lEcUtWTjVLa1I0ZmxNd3N6OVkybHlNYzdCa25KN2Y3M2g0Z3ZaOFZBb0dBQkw3N1xuVXB1cXl2RXUwTm5LZE9SOW9nV0o0akZkZGwrOFlaMXRQZVpWalUwTlZSZzhUUkdjK2VERlM1Vk8rd0p6TEhaaVxuQVBBOXhqeGtKSXhyRTE0QzhoMUcrOElBWHZWN0ZwcjBTR3JXbmtXWWlKOWlxTktpaG9laTkyTWkxK28waDdyMlxuejQ4MUpYUTJLYU1OL3ppQ2xWbC85eDhyMFZYc0J6NjZMdnF0YUJrQ2dZQVdyeGpVYmxybmFvTlBqSEdkZHNzdVxucmdvY0ZpK1hTSXFLcHcxRXkvMU54bWE1TTNRdUlYeE5qbVdxcTNrdlpaQzZ1LzVQWVZyUFhKRkxrZVdMb2tOVVxuMmZxRVpwUzl2d1hmRGVDdVcrSlIzKzh2Wkp3aGtjQjM5SFNkeVNvb3pPWkZiblV6NHFtd3NvdGgwUzQrQithL1xuUjlJY244ajgxYnlOTHBRSDZEOXVpdz09XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAia29yaS1hcHBAcGMtYXBpLTQ4Njc1MjU0NDg0ODMzMzYwOTAtNjYxLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEwNDkzMTY4MjE3NzU0ODc2OTQzMCIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkva29yaS1hcHAlNDBwYy1hcGktNDg2NzUyNTQ0ODQ4MzMzNjA5MC02NjEuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iCn0K"

jobs:

  #--------------------------
  # BUILD
  #--------------------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.10.3

      - name: Install dependencies
        run: flutter pub get

      # Creating the key.properties file
      - name: Creating key.properties
        run: |
          echo keyPassword=\${{ env.KEY_STORE }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ env.KEY_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ env.KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}
          echo storeFile=\${{ env.KEY_FILE }} >> ${{env.PROPERTIES_PATH}}
          echo "${{ env.KEYSTORE }}" | base64 --decode > ./android/keystore/upload-keystore2.jks

      - name: Build
        run: |
          flutter analyze
          flutter test
          flutter build apk --no-tree-shake-icons
          flutter build appbundle --no-tree-shake-icons


      - name: S3-Deploy-Test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          aws s3 sync \
            --acl public-read \
            --region us-east-1 \
            build/app/outputs/flutter-apk/ s3://int-wutsi/releases

      # Make appbundle downloadable
      - name: Upload app bundle
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: build/app/outputs/bundle/release

  release_internal:
    name: Release Artifacts to internal testing track
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get APPBUNDLE from Artifacts
        uses: actions/download-artifact@v2
        with:
          name: appbundle
      - name: Create Google play config file
        run: |
          echo "${{env.GOOGLE_SERVICE_JSONKEY}}" > play_config.json.b64
          base64 -d -i play_config.json.b64 > play_config.json
      - name: Release APPBUNDLE to internal track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: play_config.json
          packageName: com.wutsi.wutsi_wallet
          releaseFile: app-release.aab
          track: internal
          status: draft
          whatsNewDirectory: distribution/whatsnew
