name: master

on: [ pull_request ]

env:
  FLUTTER_VERSION: "3.3.8"
  PROPERTIES_PATH: "./android/key.properties"
  #--------------------------
  # SECRETS
  #--------------------------
  KEY_STORE: "wutsiwutsi"
  KEY_PASSWORD: "wutsiwutsi"
  KEY_ALIAS: "upload"
  KEY_FILE: "../keystore/upload-keystore2.jks"
  KEYSTORE: "${{secrets.KEYSTORE}}"
jobs:
  #--------------------------
  # BUILD
  #--------------------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{evn.FLUTTER_VERSION}}

      - name: Install dependencies
        run: flutter pub get

      # Creating the key.properties file
      - name: Creating key.properties
        run: |
          echo keyPassword=\${{ env.KEY_STORE }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ env.KEY_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ env.KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}
          echo storeFile=\${{ env.KEY_FILE }} >> ${{env.PROPERTIES_PATH}}
          echo "${{ env.KEYSTORE }}" | base64 --decode > ./android/keystore/upload-keystore2.jks

      - name: Build
        run: |
          flutter analyze
          flutter test
          flutter build apk --no-tree-shake-icons
          flutter build appbundle --no-tree-shake-icons

      # Make appbundle downloadable
      - name: Upload app bundle
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: build/app/outputs/bundle/release
